"""Sample input → output for the Fraud Intelligence system.

Two kinds of sample:
  1. sample_input.csv       real rows from data/transactions.csv; their outputs are read from
                            the batch pipeline run (outputs/), exactly what the dashboard shows.
  2. new_transactions.csv   brand-new transactions the system has never seen; each is scored
                            live against the full history (fraud/live.py), like the Scenario Lab.

Writes samples/sample_output.json and samples/sample_output.md.

Run (from the repo root, after `python -m fraud.pipeline`):
    python samples/run_samples.py
"""

import json
import pickle
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fraud.data_loader import load  # noqa: E402
from fraud.explainability import checklist, parse_reasons  # noqa: E402
from fraud.fraud_model import load_model  # noqa: E402
from fraud.live import LiveScorer  # noqa: E402

HERE = Path(__file__).resolve().parent
KEEP = ["txn_id", "timestamp", "account_id", "txn_type", "merchant_id", "merchant_name",
        "payee_account_id", "amount_inr", "device_id", "city", "country", "channel"]


def summarise(row, reasons, source, ring=None):
    return {
        "source": source,
        "input": {k: (str(row[k]) if k == "timestamp" else row[k]) for k in KEEP if k in row},
        "output": {
            "transaction_risk": float(row["transaction_risk"]),
            "behavioral_risk": float(row["behavioral_risk"]),
            "network_risk": float(row["network_risk"]),
            "final_risk": float(row["final_risk"]),
            "band": row["band"], "action": row["action"],
            "guardrail": row.get("guardrail") or "none",
            "ring_id": row.get("ring_id") or "",
            "ml_probability": float(row.get("ml_probability", 0)),
            "why": [f"✓ {c['label']} — {c['detail']}" for c in checklist(row, reasons, ring)
                    if c["hit"]],
            "reasons": [{"code": r["code"], "weight": r["weight"], "layer": r.get("layer", "rule"),
                         "evidence": r["evidence"]} for r in reasons],
            "explanation": row["explanation"],
        },
    }


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    txn = pd.read_csv(ROOT / "outputs" / "transaction_scores.csv.gz", keep_default_na=False)
    txn["timestamp"] = pd.to_datetime(txn["timestamp"])
    for c in ("network_evidence", "is_anomaly"):
        txn[c] = txn[c].astype(str).eq("True")
    rings = json.loads((ROOT / "outputs" / "rings.json").read_text("utf-8"))
    ring_by_id = {r["ring_id"]: r for r in rings}
    acc = pd.read_csv(ROOT / "outputs" / "account_scores.csv", keep_default_na=False)
    results = []

    sample = pd.read_csv(HERE / "sample_input.csv", dtype=str, keep_default_na=False)
    by_id = txn.set_index("txn_id")
    for tid in sample["txn_id"]:
        row = by_id.loc[tid].to_dict()
        row["txn_id"] = tid
        results.append(summarise(row, parse_reasons(row["reasons"]), "batch pipeline (outputs/)",
                                 ring_by_id.get(row["ring_id"])))

    tx, accounts, merchants = load()
    anomaly = {}
    try:
        with open(ROOT / "models" / "anomaly_model.pkl", "rb") as f:
            anomaly = pickle.load(f)
    except Exception:
        pass
    print("warming up the live scorer (replaying history)…")
    scorer = LiveScorer(txn, accounts, merchants, acc, rings, bundle=load_model(), anomaly=anomaly)
    new = pd.read_csv(HERE / "new_transactions.csv", dtype=str, keep_default_na=False)
    names = merchants.set_index("merchant_id")["merchant_name"].to_dict()
    for e in new.to_dict("records"):
        e["amount_inr"] = float(e["amount_inr"])
        row = scorer.score(e)
        row["merchant_name"] = names.get(row["merchant_id"], "")
        results.append(summarise(row, row["reasons"], "live scoring of a new transaction",
                                 ring_by_id.get(row["ring_id"])))

    (HERE / "sample_output.json").write_text(json.dumps(results, indent=2, ensure_ascii=False,
                                                        default=str), "utf-8")
    lines = ["# Sample output", "",
             "Generated by `python samples/run_samples.py`. Inputs: `sample_input.csv` (real rows) "
             "and `new_transactions.csv` (unseen transactions scored live).", ""]
    for r in results:
        i, o = r["input"], r["output"]
        target = i.get("merchant_name") or ("→ " + i["payee_account_id"] if i.get("payee_account_id") else "")
        lines += [f"## {i['txn_id']} — ₹{float(i['amount_inr']):,.2f} {target}",
                  f"*{r['source']}* · {i['timestamp']} · account {i['account_id']} · device "
                  f"{i.get('device_id') or 'card-present'} · {i['city']}, {i['country']}", "",
                  "| Transaction | Behavioral | Network | **Final** | Band | Action |",
                  "|---|---|---|---|---|---|",
                  f"| {o['transaction_risk']:.0f} | {o['behavioral_risk']:.0f} | "
                  f"{o['network_risk']:.0f} | **{o['final_risk']:.0f}** | {o['band']} | "
                  f"**{o['action']}** |", ""]
        lines += [f"- {w}" for w in o["why"]] or ["- no warning signs"]
        lines += ["", f"> {o['explanation']}", ""]
        print(f"{i['txn_id']:9s} ₹{float(i['amount_inr']):>12,.2f}  T {o['transaction_risk']:5.1f} "
              f"B {o['behavioral_risk']:5.1f} N {o['network_risk']:5.1f} → final "
              f"{o['final_risk']:5.1f} {o['band']:8s} {o['action']}")
    (HERE / "sample_output.md").write_text("\n".join(lines), "utf-8")
    print("wrote samples/sample_output.json and samples/sample_output.md")


if __name__ == "__main__":
    main()
